services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-aventuras
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: aventuras_db
      MYSQL_USER: aventuras_user
      MYSQL_PASSWORD: aventuras_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  userservice:
    container_name: userservice
    build:
      context: ./userservice
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/aventuras_db
      SPRING_DATASOURCE_USERNAME: aventuras_user
      SPRING_DATASOURCE_PASSWORD: aventuras_pass
    ports:
      - "8081:8080"

  postservice:
    container_name: postservice
    build:
      context: ./postservice
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/aventuras_db
      SPRING_DATASOURCE_USERNAME: aventuras_user
      SPRING_DATASOURCE_PASSWORD: aventuras_pass
    ports:
      - "8082:8080"

volumes:
  mysql_data:
