services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-aventuras
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aventura_posts
      MYSQL_USER: aventuras_user
      MYSQL_PASSWORD: aventuras_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-aventuras
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  userservice:
    container_name: userservice
    build:
      context: ./userservice
    depends_on:
      - mysql-db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/aventuras_db
      SPRING_DATASOURCE_USERNAME: aventuras_user
      SPRING_DATASOURCE_PASSWORD: aventuras_pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "8080:8080"

  postservice:
    container_name: postservice
    build:
      context: ./postservice
    depends_on:
      - mysql-db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/aventura_posts
      SPRING_DATASOURCE_USERNAME: aventuras_user
      SPRING_DATASOURCE_PASSWORD: aventuras_pass
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - "8081:8081"

volumes:
  mysql_data:
  rabbitmq_data:
