# Configuración para desarrollo local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aventura_posts?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.aca.postservice: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.security: DEBUG
